modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="invincible_conquest"
version="5.0.0"
displayName="Invincible: Conquest"
displayURL="https://discord.gg/TJj3Sk52Jq"
credits="sushiclozy, NoiiLive"
authors="sushiclozy, NoiiLive"
description="Adds Invincible into Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.invincible_conquest]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.invincible_conquest]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.invincible_conquest]]
    modId="kleidersplayerrenderer"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invincible_conquest]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invincible_conquest]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration